# Generated by Django 4.2.1 on 2023-05-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
