# Generated by Django 4.2.1 on 2023-06-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_address_customer_address_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
