# Generated by Django 4.2.1 on 2023-07-27 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_comment_ip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
