# Generated by Django 4.2.1 on 2023-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Default Name', max_length=200, null=True),
        ),
    ]
