# Generated by Django 4.2.1 on 2023-08-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_is_admin_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_admin_product',
            field=models.BooleanField(default=False),
        ),
    ]
