# Generated by Django 4.2.1 on 2023-08-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_is_admin_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_admin_product',
        ),
        migrations.AddField(
            model_name='order',
            name='is_admin_product',
            field=models.BooleanField(default=True),
        ),
    ]
