# Generated by Django 4.2.1 on 2023-08-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
