# Generated by Django 4.2.1 on 2023-08-24 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_comment_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
