# Generated by Django 4.2.1 on 2023-08-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_order_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='subject',
        ),
    ]
